### ISSUE TITLE
Complete Digital Signal Control using RP2 Assembly

### ISSUE THREAD

**Issue by Ahmed-Waseem77** [AUC-Hardware/SI-Testing#11]
uncovered in issue #8

---

When generating signals any two successive toggles for a PIO pin has about 20 us ON (or OFF) period, (This was verified with an oscilloscope).

For our use case we would need greater control in ns scale for greater efficiency thus the need for RP2 assembly digital signal controllers.

Goal is to construct a general class or a function for digital signal generation in us.
RP2 has around 125MHZ so the cycle takes around 8ns.

**Comment by shalan** [comment]
Not sure about the need for this.
The process we are controlling is slow; there is no need for us DIO resolution.

**Comment by Ahmed-Waseem77** [comment]
Noted, closing the issue!
